# bulk-seq ALS data (lumbar spinal cord and cortex)
# lumbar spinal cord expression data downloaded from https://zenodo.org/records/6385747
# Kuo 20260330


pacman::p_load(data.able, ggplot2, ggpubr, ggsci, ggrepel, patchwork)


#### lumbar spinal cord ####
# read in data
tpm <- read.table('./Lumbar_Spinal_Cord/Lumbar_Spinal_Cord_gene_tpm.tsv', header = T, row.names = 1, sep = '\t')
meta <- read.table('./Lumbar_Spinal_Cord/Lumbar_Spinal_Cord_metadata.tsv', header = T, row.names = 1, sep = '\t')
table(duplicated(tpm$gene_name))
#FALSE  TRUE 
#57317  1567 

gene <- c('COL1A1','COL1A2','DCN','LUM','THBS2','CLDN1','GADL1') # COL1A2

df <- tpm[which(tpm$gene_name %in% gene),]
rownames(df) <- df$gene_name
df <- df[,-1]
df <- as.data.frame(t(df))
df <- cbind(df,meta[rownames(df),c('disease','disease_duration')])
df$disease <- ifelse(df$disease=='Control','Control','ALS') # for some case is ALS-FTD

library(ggplot2)
library(ggpubr)
library(ggsci)

df2 <- reshape2::melt(df, id.vars = c('disease','disease_duration'), variable.name = 'gene', value.name = 'expression')
df2$gene <- factor(df2$gene, levels = gene)
df2$disease <- factor(df2$disease,levels = c('Control','ALS'))

theme_set(theme_grey(base_family = "sans")) 
pdf('./Lumbar_Spinal_Cord_boxplot.pdf', width = 10, height = 5)
ggplot(df2, aes(x=disease, y=expression)) +
  geom_boxplot(aes(fill = disease),outlier.shape = NA) +
  #geom_jitter(aes(color=disease),position = position_jitter(width = 0.2),) +
  geom_jitter(aes(fill = disease),
              shape = 21,
              color = "black",
              width = 0.2,
              size = 1.5,
              stroke = 0.6,
              alpha = 0.8)+
  facet_wrap(~gene,scales='free',ncol=length(gene))+
  #theme_classic() +
  labs(title = 'Bulk RNA-seq of human lumbar spinal cord') +
  stat_compare_means(method = 'wilcox.test',
                     comparisons = list(c("Control","ALS")),
                     label = "p.signif") +
  theme(
    axis.text = element_text(color = 'black'),
    strip.background = element_rect(fill = "lightblue", color = 'black'),
    strip.text = element_text(face='italic') 
  )+ scale_fill_manual(values = c('#4DBBD5','#E64B35'))+
  scale_color_manual(values = c('#4DBBD5','#E64B35'))
# scale_fill_npg()+scale_color_npg()
dev.off()
# fig 4B
ggsave('Lumbar_Spinal_Cord_boxplot.pdf',plot = p,width = 10, height = 4)


#### cortex ####

library(GEOquery)   
library(stringr)  
library(dplyr)

# data from GSE137810, which covered 2906 samples
# the sample meta data is downloaded from https://ftp.ncbi.nlm.nih.gov/geo/series/GSE137nnn/GSE137810/matrix/
# two files (platforms) are porvided, GPL24676 and GPL24677, which are generated by two different sequencing platforms (Illumina NovaSeq 6000 and Illumina HiSeq 4000, respectively).
# the count data is downloaded from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE137810#:~:text=144.7%20Mb-,(http),-(custom)
# However only 731 samples have count data
# Two different platforms (GPL24676 and GPL24677) are used for sequencing, 
# and the count data is only available for samples sequenced by GPL24676 (555/731). 
# Therefore, we will only use the samples sequenced by GPL24676 for downstream analysis. 
# also considering the tech-batch, combining two platforms may not be a good idea.


setwd('./bulk-seq/cortex')

# count files
files <- list.files('./bulk-seq/cortex/GSE137810_RAW/', pattern = 'counts.txt.gz', full.names = F)
samples <- sapply(strsplit(files,'_'), '[',2)
ges <- sapply(strsplit(files,'_'), '[',1)
table(duplicated(samples)) # FALSE 713  TRUE  18 
table(duplicated(ges)) # unique sample names and unique GEO accessions


# process meta 1 (GPL24676)
# selected 5 fields: sample_geo_accession, tissue, subject id, group, sample id alt from GSE137810-GPL24676_series_matrix.txt.gz
meta <- read.csv('./GSE137810-GPL24676_series_matrix_selected_0423.csv',header = F)
meta <- meta[,c(1,which(meta[3,] %in% ges))]
meta <- meta[c(3,9,12,13,14),]
m <- c('sample_geo_accession','tissue','disease state','gender','subject id')
rownames(meta) <- m
meta$V1 <- NULL
for (field in m) {
  meta[field,] <- str_replace(meta[field,], paste0(field, ': '), '')
}
meta <- t(meta) %>% as.data.frame()
rownames(meta) <- meta$sample_geo_accession
spinalcord <- grepl('spinal cord',meta$tissue,ignore.case = T)
meta_ctx <- meta[!spinalcord,] # I only want ctx data here, not spinal cord samples
meta_ctx <- subset(meta_ctx,meta_ctx$`disease state` %in% c('ALS','CTL')) # only keep control and SALS samples)


for(i in seq_along(files)){
  print(i)
  count <- data.table::fread(paste0('./GSE137810_RAW/',files[i]))
  colnames(count) <- c('gene_name',ges[i])
  if(!exists('count_all')){
    count_all <- count
  }else{
    count_all <- merge(count_all, count, by = 'gene_name', all = T)
  }
}
write.csv(count_all,'./GSE137810_count_all.csv',row.names = F)
count_all <- read.csv('./GSE137810_count_all.csv')



# gene exploration
sam <- intersect(meta_ctx$sample_geo_accession,ges)
count <- count_all[,c('gene_name',sam)]
rownames(count) <- count$gene_name
count$gene_name <- NULL


data <- list(count = count,meta = meta_ctx)
saveRDS(data,'./GSE137810_count_meta_ctx.rds')
# data <- readRDS('./GSE137810_count_meta_ctx.rds')
# count <- data$count
# meta_ctx <- data$meta

#gene <- c('COL1A1','COL1A2','DCN','LUM','THBS2','CLDN1','GADL1','BICC1','TIAM1') 
gene <- c('COL1A1','COL1A2','DCN','LUM','THBS2','CLDN1','GADL1')

df <- count[gene,] %>% t() %>% as.data.frame()
df$disease <- meta_ctx[colnames(count),'disease state']

df2 <- reshape2::melt(df, id.vars = c('disease'), variable.name = 'gene', value.name = 'expression')
df2$gene <- factor(df2$gene, level = gene)

library(ggplot2)
library(ggpubr)
theme_set(theme_grey(base_family = "sans")) 

df2$disease <- factor(df2$disease,levels = c('CTL','ALS'))

theme_set(theme_grey(base_family = "sans")) 
p <- ggplot(df2, aes(x=disease, y=expression)) +
  geom_boxplot(aes(fill = disease),outlier.shape = NA) +
  #geom_jitter(aes(color=disease),position = position_jitter(width = 0.2),) +
  geom_jitter(aes(fill = disease),
              shape = 21,
              color = "black",
              width = 0.2,
              size = 1.5,
              stroke = 0.6,
              alpha = 0.8)+
  facet_wrap(~gene,scales='free',ncol=length(gene))+
  #theme_classic() +
  labs(title = 'Bulk RNA-seq of human cortex') +
  stat_compare_means(method = 'wilcox.test',
                     comparisons = list(c("CTL","ALS")),
                     label = "p.signif") +
  theme(
    axis.text = element_text(color = 'black'),
    strip.background = element_rect(fill = "lightblue", color = 'black'),
    strip.text = element_text(face='italic') 
  )+ scale_fill_manual(values = c('#4DBBD5','#E64B35'))+
  scale_color_manual(values = c('#4DBBD5','#E64B35'))

# fig S3C
ggsave('bulk_Cortex_boxplot.pdf',plot = p,width = 12, height = 4)# scale_fill_npg()+scale_color_npg()ggsave('Lumbar_Spinal_Cord_boxplot.pdf',plot = p,width = 10, height = 5)


